In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/DataCoSupplyChainDataset.csv", encoding="latin1")

In [4]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [5]:
df.shape

(180519, 53)

In [6]:
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [8]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [9]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
clean_df = df.copy()

In [12]:
columns_to_remove = [
    "Product Description",
    "Product Image",
    "Customer Password",
    "Customer Street",
    "Customer Email"
]

clean_df = clean_df.drop(columns=columns_to_remove)

In [13]:
clean_df.shape

(180519, 48)

In [14]:
clean_df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Segment',
 'Customer State',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [15]:
clean_df[['order date (DateOrders)', 'shipping date (DateOrders)']].head()

  order date (DateOrders) shipping date (DateOrders)
0         1/31/2018 22:56             2/3/2018 22:56
1         1/13/2018 12:27            1/18/2018 12:27
2         1/13/2018 12:06            1/17/2018 12:06
3         1/13/2018 11:45            1/16/2018 11:45
4         1/13/2018 11:24            1/15/2018 11:24

In [16]:
clean_df[['order date (DateOrders)', 'shipping date (DateOrders)']].dtypes

order date (DateOrders)       str
shipping date (DateOrders)    str
dtype: object

In [17]:
clean_df['order date (DateOrders)'] = pd.to_datetime(
    clean_df['order date (DateOrders)']
)

clean_df['shipping date (DateOrders)'] = pd.to_datetime(
    clean_df['shipping date (DateOrders)']
)

In [18]:
clean_df[['order date (DateOrders)', 'shipping date (DateOrders)']].dtypes

order date (DateOrders)       datetime64[us]
shipping date (DateOrders)    datetime64[us]
dtype: object

In [19]:
clean_df['Order_Year'] = clean_df['order date (DateOrders)'].dt.year

In [20]:
clean_df['Order_Month'] = clean_df['order date (DateOrders)'].dt.month

In [21]:
clean_df['Order_Month_Name'] = clean_df['order date (DateOrders)'].dt.month_name()

In [22]:
clean_df['Order_Day'] = clean_df['order date (DateOrders)'].dt.day_name()

In [23]:
clean_df[['Order_Year','Order_Month','Order_Month_Name','Order_Day']].head()

   Order_Year  Order_Month Order_Month_Name  Order_Day
0        2018            1          January  Wednesday
1        2018            1          January   Saturday
2        2018            1          January   Saturday
3        2018            1          January   Saturday
4        2018            1          January   Saturday

In [24]:
clean_df.isnull().sum()[clean_df.isnull().sum() > 0]

Customer Lname           8
Customer Zipcode         3
Order Zipcode       155679
dtype: int64

In [25]:
clean_df['Customer Lname'] = clean_df['Customer Lname'].fillna('Unknown')

In [26]:
clean_df['Customer Zipcode'] = clean_df['Customer Zipcode'].fillna(0)

In [27]:
clean_df = clean_df.drop(columns=['Order Zipcode'])

In [28]:
clean_df.isnull().sum()[clean_df.isnull().sum() > 0]

Series([], dtype: int64)

In [29]:
clean_df.shape

(180519, 51)

In [30]:
customers = clean_df[
[
'Customer Id',
'Customer Fname',
'Customer Lname',
'Customer Segment',
'Customer City',
'Customer State',
'Customer Country',
'Customer Zipcode'
]
]

In [31]:
customers = customers.drop_duplicates()

In [32]:
customers.shape

(20652, 8)

In [33]:
customers.head()

,Customer Id,Customer Fname,Customer Lname,Customer Segment,Customer City,Customer State,Customer Country,Customer Zipcode
0,20755,Cally,Holloway,Consumer,Caguas,PR,Puerto Rico,725.0
1,19492,Irene,Luna,Consumer,Caguas,PR,Puerto Rico,725.0
2,19491,Gillian,Maldonado,Consumer,San Jose,CA,EE. UU.,95125.0
3,19490,Tana,Tate,Home Office,Los Angeles,CA,EE. UU.,90027.0
4,19489,Orli,Hendricks,Corporate,Caguas,PR,Puerto Rico,725.0

In [34]:
products = clean_df[
[
'Product Card Id',
'Product Name',
'Category Id',
'Category Name',
'Department Id',
'Department Name',
'Product Price',
'Product Status'
]
]

In [36]:
products = products.drop_duplicates()

In [37]:
products.shape

(118, 8)

In [38]:
products.head()

,Product Card Id,Product Name,Category Id,Category Name,Department Id,Department Name,Product Price,Product Status
0,1360,Smart watch,73,Sporting Goods,2,Fitness,327.750000,0
48,365,Perfect Fitness Perfect Rip Deck,17,Cleats,4,Apparel,59.990002,0
49,627,Under Armour Girls' Toddler Spine Surge Runni,29,Shop By Sport,5,Golf,39.990002,0
50,502,Nike Men's Dri-FIT Victory Golf Polo,24,Women's Apparel,5,Golf,50.000000,0
55,278,Under Armour Men's Compression EV SL Slide,13,Electronics,3,Footwear,44.990002,0

In [39]:
orders = clean_df[
[
'Order Id',
'Order Customer Id',
'order date (DateOrders)',
'Order Status',
'Market',
'Order Region',
'Order Country',
'Order State',
'Order City'
]
]

In [40]:
orders = orders.drop_duplicates()

In [41]:
orders.shape

(65752, 9)

In [ ]:
orders.head()

,Order Id,Order Customer Id,order date (DateOrders),Order Status,Market,Order Region,Order Country,Order State,Order City
0,77202,20755,2018-01-31 22:56:00,COMPLETE,Pacific Asia,Southeast Asia,Indonesia,Java Occidental,Bekasi
1,75939,19492,2018-01-13 12:27:00,PENDING,Pacific Asia,South Asia,India,Rajastán,Bikaner
2,75938,19491,2018-01-13 12:06:00,CLOSED,Pacific Asia,South Asia,India,Rajastán,Bikaner
3,75937,19490,2018-01-13 11:45:00,COMPLETE,Pacific Asia,Oceania,Australia,Queensland,Townsville
4,75936,19489,2018-01-13 11:24:00,PENDING_PAYMENT,Pacific Asia,Oceania,Australia,Queensland,Townsville

In [43]:
order_items = clean_df[
[
'Order Item Id',
'Order Id',
'Product Card Id',
'Order Item Quantity',
'Order Item Discount',
'Order Item Discount Rate',
'Order Item Product Price',
'Order Item Total'
]
]

In [44]:
order_items = order_items.drop_duplicates()

In [45]:
order_items.shape

(180519, 8)

In [46]:
order_items.head()

,Order Item Id,Order Id,Product Card Id,Order Item Quantity,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Order Item Total
0,180517,77202,1360,1,13.110000,0.04,327.75,314.640015
1,179254,75939,1360,1,16.389999,0.05,327.75,311.359985
2,179253,75938,1360,1,18.030001,0.06,327.75,309.720001
3,179252,75937,1360,1,22.940001,0.07,327.75,304.809998
4,179251,75936,1360,1,29.500000,0.09,327.75,298.250000

In [47]:
shipments = clean_df[
[
'Order Id',
'Shipping Mode',
'shipping date (DateOrders)',
'Days for shipping (real)',
'Days for shipment (scheduled)',
'Delivery Status',
'Late_delivery_risk'
]
]

In [48]:
shipments = shipments.drop_duplicates()

In [49]:
shipments.shape

(65752, 7)

In [50]:
shipments.head()

,Order Id,Shipping Mode,shipping date (DateOrders),Days for shipping (real),Days for shipment (scheduled),Delivery Status,Late_delivery_risk
0,77202,Standard Class,2018-02-03 22:56:00,3,4,Advance shipping,0
1,75939,Standard Class,2018-01-18 12:27:00,5,4,Late delivery,1
2,75938,Standard Class,2018-01-17 12:06:00,4,4,Shipping on time,0
3,75937,Standard Class,2018-01-16 11:45:00,3,4,Advance shipping,0
4,75936,Standard Class,2018-01-15 11:24:00,2,4,Advance shipping,0

In [51]:
financials = clean_df[
[
'Order Id',
'Sales',
'Benefit per order',
'Order Profit Per Order',
'Order Item Profit Ratio',
'Sales per customer'
]
]

In [52]:
financials = financials.drop_duplicates()

In [53]:
financials.shape

(180519, 6)

In [54]:
financials.head()

,Order Id,Sales,Benefit per order,Order Profit Per Order,Order Item Profit Ratio,Sales per customer
0,77202,327.75,91.250000,91.250000,0.29,314.640015
1,75939,327.75,-249.089996,-249.089996,-0.80,311.359985
2,75938,327.75,-247.779999,-247.779999,-0.80,309.720001
3,75937,327.75,22.860001,22.860001,0.08,304.809998
4,75936,327.75,134.210007,134.210007,0.45,298.250000

In [55]:
financials['Sales'].sum()

np.float64(36784735.01337984)

In [56]:
locations = clean_df[
[
'Order Country',
'Order Region',
'Latitude',
'Longitude',
'Market'
]
]

In [57]:
locations = locations.drop_duplicates()

In [58]:
locations.shape

(54812, 5)

In [59]:
locations.head()

  Order Country    Order Region   Latitude   Longitude        Market
0     Indonesia  Southeast Asia  18.251453  -66.037056  Pacific Asia
1         India      South Asia  18.279451  -66.037064  Pacific Asia
2         India      South Asia  37.292233 -121.881279  Pacific Asia
3     Australia         Oceania  34.125946 -118.291016  Pacific Asia
4     Australia         Oceania  18.253769  -66.037048  Pacific Asia

In [60]:
customers.to_csv(
    "../data/processed/customers.csv",
    index=False
)

In [61]:
products.to_csv(
    "../data/processed/products.csv",
    index=False
)

In [62]:
orders.to_csv(
    "../data/processed/orders.csv",
    index=False
)

In [63]:
order_items.to_csv(
    "../data/processed/order_items.csv",
    index=False
)

In [64]:
shipments.to_csv(
    "../data/processed/shipments.csv",
    index=False
)

In [65]:
financials.to_csv(
    "../data/processed/financials.csv",
    index=False
)

In [66]:
locations.to_csv(
    "../data/processed/locations.csv",
    index=False
)

In [67]:
import os

os.listdir("../data/processed")

['customers.csv',
 'financials.csv',
 'locations.csv',
 'orders.csv',
 'order_items.csv',
 'products.csv',
 'shipments.csv']